# Generated by Django 5.0.6 on 2024-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='minimum_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='recommended_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
