# Generated by Django 5.0.6 on 2024-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_minimum_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
