# Generated by Django 5.0.6 on 2024-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='price',
            new_name='price_final',
        ),
        migrations.RemoveField(
            model_name='games',
            name='header_image',
        ),
        migrations.AddField(
            model_name='games',
            name='capsule_image',
            field=models.ImageField(blank=True, default='', upload_to='games/capsule_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='games',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='price_initial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='sale_image',
            field=models.ImageField(blank=True, default='', upload_to='games/sale_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='games',
            name='screenshot5',
            field=models.ImageField(blank=True, default='', upload_to='games/screenshots/%Y/%m/%d/'),
        ),
    ]
