# Generated by Django 5.0.6 on 2024-07-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_price_games_price_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='movie1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='movie2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='movie3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='background_raw',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='sale_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='screenshot1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='screenshot2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='screenshot3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='screenshot4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='games',
            name='screenshot5',
            field=models.CharField(max_length=500),
        ),
    ]
