# Generated by Django 5.0.6 on 2024-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_games_movie1_games_movie2_games_movie3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
