# Generated by Django 5.0.6 on 2024-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.ManyToManyField(blank=True, default='', to='games.genres'),
        ),
    ]
