# Generated by Django 5.0.6 on 2024-07-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_games_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('total_reviews', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_positive', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_negative', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.reviews'),
        ),
    ]
