# Generated by Django 5.0.6 on 2024-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_reviews_games_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='total_negative',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='total_positive',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='total_reviews',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
