# Generated by Django 5.0.6 on 2024-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_reviews_positive_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='positive_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
