# Generated by Django 5.0.6 on 2024-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_reviews_positive_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
