# Generated by Django 5.0.6 on 2024-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_games_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='background',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
