# Generated by Django 5.0.6 on 2024-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_games_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
