# Generated by Django 5.0.6 on 2024-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_games_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='about_the_game',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='app_reviews',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='controller_support',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='languages',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='legal_notice',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='metacritic_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='pegi_rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='required_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
