# Generated by Django 5.0.6 on 2024-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_games_about_the_game_games_app_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='currently_popular',
            field=models.BooleanField(default=False),
        ),
    ]
