# Generated by Django 5.0.6 on 2024-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_games_currently_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='required_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
